language: node_js

node_js:
  - 8
  - 6

before_install:
  - "npm install angular-docgen"

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release